[package]
name = "launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
rust-ini = "0.21"
ratatui = "0.28.1"
serde = { version = "1.0.210", features = ["derive"] }
toml = "0.8.19"
phf = { version = "0.11.3", features = ["macros"] }
nix = { version = "0.29.0", features = ["process", "signal"] }
procfs = "0.17.0"
chrono = "0.4.39"
