[[entries]]
name = "About"
launch_count = 0
blacklisted = false

[[entries]]
name = "Access Prompt"
launch_count = 0
blacklisted = false

[[entries]]
name = "Accessibility"
launch_count = 0
blacklisted = false

[[entries]]
name = "Advanced Network Configuration"
launch_count = 0
blacklisted = false

[[entries]]
name = "Alacritty"
launch_count = 0
blacklisted = false

[[entries]]
name = "Appearance"
launch_count = 0
blacklisted = false

[[entries]]
name = "Apps"
launch_count = 0
blacklisted = false

[[entries]]
name = "Avahi SSH Server Browser"
launch_count = 0
blacklisted = false

[[entries]]
name = "Avahi VNC Server Browser"
launch_count = 0
blacklisted = false

[[entries]]
name = "Avahi Zeroconf Browser"
launch_count = 0
blacklisted = false

[[entries]]
name = "Bluetooth"
launch_count = 1
blacklisted = false

[[entries]]
name = "Bluetooth Transfer"
launch_count = 0
blacklisted = false

[[entries]]
name = "Calculator"
launch_count = 0
blacklisted = false

[[entries]]
name = "Calendar"
launch_count = 0
blacklisted = false

[[entries]]
name = "Camera"
launch_count = 0
blacklisted = false

[[entries]]
name = "Clocks"
launch_count = 0
blacklisted = false

[[entries]]
name = "Color Management"
launch_count = 0
blacklisted = false

[[entries]]
name = "Color Picker"
launch_count = 0
blacklisted = false

[[entries]]
name = "Color Profile Viewer"
launch_count = 0
blacklisted = false

[[entries]]
name = "Connections"
launch_count = 0
blacklisted = false

[[entries]]
name = "Console"
launch_count = 0
blacklisted = false

[[entries]]
name = "Contacts"
launch_count = 0
blacklisted = false

[[entries]]
name = "Date & Time"
launch_count = 0
blacklisted = false

[[entries]]
name = "Disk Image Mounter"
launch_count = 0
blacklisted = false

[[entries]]
name = "Disk Image Writer"
launch_count = 0
blacklisted = false

[[entries]]
name = "Disk Usage Analyzer"
launch_count = 0
blacklisted = false

[[entries]]
name = "Disks"
launch_count = 0
blacklisted = false

[[entries]]
name = "Displays"
launch_count = 0
blacklisted = false

[[entries]]
name = "Document Scanner"
launch_count = 0
blacklisted = false

[[entries]]
name = "Document Viewer"
launch_count = 0
blacklisted = false

[[entries]]
name = "Events and Tasks Reminders"
launch_count = 0
blacklisted = false

[[entries]]
name = "Evolution Data Server OAuth2 Handler"
launch_count = 0
blacklisted = false

[[entries]]
name = "Extension Manager"
launch_count = 0
blacklisted = false

[[entries]]
name = "File Sharing"
launch_count = 0
blacklisted = false

[[entries]]
name = "Files"
launch_count = 0
blacklisted = false

[[entries]]
name = "Firefox"
launch_count = 0
blacklisted = false

[[entries]]
name = "Fonts"
launch_count = 0
blacklisted = false

[[entries]]
name = "Geoclue Demo agent"
launch_count = 0
blacklisted = false

[[entries]]
name = "Ghostty"
launch_count = 0
blacklisted = false

[[entries]]
name = "GNOME Remote Desktop Handover Daemon"
launch_count = 0
blacklisted = false

[[entries]]
name = "GNOME System Monitor"
launch_count = 0
blacklisted = false

[[entries]]
name = "GNU Image Manipulation Program"
launch_count = 0
blacklisted = false

[[entries]]
name = "Google Chrome"
launch_count = 0
blacklisted = false

[[entries]]
name = "Graphics Tablets"
launch_count = 0
blacklisted = false

[[entries]]
name = "Hardware Locality lstopo"
launch_count = 0
blacklisted = false

[[entries]]
name = "Helix"
launch_count = 0
blacklisted = false

[[entries]]
name = "Help"
launch_count = 0
blacklisted = false

[[entries]]
name = "Htop"
launch_count = 0
blacklisted = false

[[entries]]
name = "ICC Profile Installer"
launch_count = 0
blacklisted = false

[[entries]]
name = "Image Viewer"
launch_count = 0
blacklisted = false

[[entries]]
name = "Keyboard"
launch_count = 0
blacklisted = false

[[entries]]
name = "LibreOffice"
launch_count = 0
blacklisted = false

[[entries]]
name = "LibreOffice Base"
launch_count = 0
blacklisted = false

[[entries]]
name = "LibreOffice Calc"
launch_count = 0
blacklisted = false

[[entries]]
name = "LibreOffice Draw"
launch_count = 0
blacklisted = false

[[entries]]
name = "LibreOffice Impress"
launch_count = 0
blacklisted = false

[[entries]]
name = "LibreOffice Math"
launch_count = 0
blacklisted = false

[[entries]]
name = "LibreOffice Writer"
launch_count = 0
blacklisted = false

[[entries]]
name = "LibreOffice XSLT based filters"
launch_count = 0
blacklisted = false

[[entries]]
name = "Logs"
launch_count = 0
blacklisted = false

[[entries]]
name = "Manage Printing"
launch_count = 0
blacklisted = false

[[entries]]
name = "Microsoft Edge"
launch_count = 0
blacklisted = false

[[entries]]
name = "Mobile Network"
launch_count = 0
blacklisted = false

[[entries]]
name = "Mouse & Touchpad"
launch_count = 0
blacklisted = false

[[entries]]
name = "Multitasking"
launch_count = 0
blacklisted = false

[[entries]]
name = "Music"
launch_count = 0
blacklisted = false

[[entries]]
name = "Neovim"
launch_count = 0
blacklisted = false

[[entries]]
name = "Network"
launch_count = 0
blacklisted = false

[[entries]]
name = "NetworkManager Applet"
launch_count = 0
blacklisted = false

[[entries]]
name = "Notifications"
launch_count = 0
blacklisted = false

[[entries]]
name = "Online Accounts"
launch_count = 0
blacklisted = false

[[entries]]
name = "Parental Controls"
launch_count = 0
blacklisted = false

[[entries]]
name = "Power"
launch_count = 0
blacklisted = false

[[entries]]
name = "Print Preview"
launch_count = 0
blacklisted = false

[[entries]]
name = "Printers"
launch_count = 0
blacklisted = false

[[entries]]
name = "Privacy & Security"
launch_count = 0
blacklisted = false

[[entries]]
name = "Qt V4L2 test Utility"
launch_count = 0
blacklisted = false

[[entries]]
name = "Qt V4L2 video capture utility"
launch_count = 0
blacklisted = false

[[entries]]
name = "QtQR"
launch_count = 0
blacklisted = false

[[entries]]
name = "R"
launch_count = 0
blacklisted = false

[[entries]]
name = "ranger"
launch_count = 0
blacklisted = false

[[entries]]
name = "Region & Language"
launch_count = 0
blacklisted = false

[[entries]]
name = "Run Software"
launch_count = 0
blacklisted = false

[[entries]]
name = "Rygel"
launch_count = 0
blacklisted = false

[[entries]]
name = "Rygel Preferences"
launch_count = 0
blacklisted = false

[[entries]]
name = "Search"
launch_count = 0
blacklisted = false

[[entries]]
name = "Settings"
launch_count = 0
blacklisted = false

[[entries]]
name = "Sharing"
launch_count = 0
blacklisted = false

[[entries]]
name = "Software"
launch_count = 0
blacklisted = false

[[entries]]
name = "Software Install"
launch_count = 0
blacklisted = false

[[entries]]
name = "Software Install"
launch_count = 0
blacklisted = false

[[entries]]
name = "Sound"
launch_count = 0
blacklisted = false

[[entries]]
name = "Spotify"
launch_count = 0
blacklisted = false

[[entries]]
name = "System"
launch_count = 0
blacklisted = false

[[entries]]
name = "System Monitor"
launch_count = 0
blacklisted = false

[[entries]]
name = "Tecla"
launch_count = 0
blacklisted = false

[[entries]]
name = "Text Editor"
launch_count = 0
blacklisted = false

[[entries]]
name = "Tour"
launch_count = 0
blacklisted = false

[[entries]]
name = "Tweaks"
launch_count = 0
blacklisted = false

[[entries]]
name = "User folders update"
launch_count = 0
blacklisted = false

[[entries]]
name = "Users"
launch_count = 0
blacklisted = false

[[entries]]
name = "Videos"
launch_count = 0
blacklisted = false

[[entries]]
name = "View file"
launch_count = 0
blacklisted = false

[[entries]]
name = "Vim"
launch_count = 0
blacklisted = false

[[entries]]
name = "Web"
launch_count = 0
blacklisted = false

[[entries]]
name = "Wellbeing"
launch_count = 0
blacklisted = false

[[entries]]
name = "Where am I?"
launch_count = 0
blacklisted = false

[[entries]]
name = "Wi-Fi"
launch_count = 0
blacklisted = false

[[entries]]
name = "Xwayland"
launch_count = 0
blacklisted = false

[[entries]]
name = "Yazi"
launch_count = 0
blacklisted = false
