# [input]
# placeholder = "Search Applications"

# [counter]
# enable = true

# color_mode = "light"

[border]
enable_border = false
divider_character = ' '
margin = { x = 1, y = 0 }

[application_list]
# display_icons = false

[info]
# enable = true
