# [input]
# placeholder = "Search Applications"

# [counter]
# enable = true

[border]
enable_border = false
divider_character = ' '

# [application_list]
# display_icons = true

# [debug]
# enable = false
