[input]
placeholder = "Search Applications"

[counter]
enable = true

[border]
margin = { x = 2, y = 1 }
enable_border = false
divider_character = ' '

[application_list]
display_icons = true

[debug]
enable = false
